# Glome API - OAuth2 middleware
glome_api:
    resource: "@GlomeApiBundle/Controller/"
    type:     annotation
    prefix:   /

glome_services:
    resource: "@GlomeApiBundle/Resources/config/routing.yml"


# Nelmio API doc bundle
NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc


# FOS OAuth Server
fos_oauth_server_token:
    resource: "@GlomeApiBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
