security:
    encoders:
        Glome\ApiBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        # in_memory:
        #     memory:
        #         users:
        #             restapi:  { password: secretpw2, roles: [ 'ROLE_API' ] }
        user_provider:
            id: glome_api.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            stateless:  true
            http_basic:
                realm: "Demo REST API (username: restapi, password: secretpw)"


        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            fos_oauth:	true # Add your favorite authentication process here

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true # can be omitted as its default value

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
