parameters:
#    glome_api.example.class: Glome\ApiBundle\Example
    glome.entity.user.class: Glome\ApiBundle\Entity\User
    glome.user.provider.class: Glome\ApiBundle\Provider\UserProvider

services:
#    glome_api.example:
#        class: %glome_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    glome.user.manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManagerForClass
        arguments: ["%glome.entity.user.class%"]

    glome.user.repository:
        class: Glome\ApiBundle\Repository\UserRepository
        factory_service: glome.user.manager
        factory_method: getRepository
        arguments: ["%glome.entity.user.class%"]

    glome.user.provider:
        class: "%glome.user.provider.class%"
        arguments: ["@glome.user.repository"]
