parameters:
#    glome_api.example.class: Glome\ApiBundle\Example

#     glome_api.entity.user.class: Glome\ApiBundle\Entity\User
    glome_api.entity.user.class: Symfony\Component\Security\Core\User\User
    glome_api.user.provider.class: Glome\ApiBundle\Provider\UserProvider
    glome_api.token.controller.class: Glome\ApiBundle\Controller\TokenController

    glome_api.users:
      restapi:
          password: secretpw
          roles:
              - 'ROLE_API'

    glome_api.auth_code_manager.class: Glome\ApiBundle\Entity\AuthCodeManager

    glome_api.user.class: Glome\ApiBundle\Entity\User
    glome_api.auth_code.class: Glome\ApiBundle\Entity\AuthCode

    glome_api.oauth.storage.class: Glome\ApiBundle\Storage\GlomeOAuthStorage
    glome_api.oauth.server.class: Glome\ApiBundle\Lib\GlomeOAuth2

services:
#    glome_api.example:
#        class: %glome_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#     glome_api.user.manager:
#         class: Doctrine\ORM\EntityManager
#         factory_service: doctrine
#         factory_method: getManagerForClass
#         arguments: ["%glome_api.entity.user.class%"]
#
#     glome_api.user.repository:
#         class: Glome\ApiBundle\Entity\UserRepository
#         factory_service: glome_api.user.manager
#         factory_method: getRepository
#         arguments: ["%glome_api.entity.user.class%"]

    glome_api.user.provider:
        class: "%glome_api.user.provider.class%"
        # arguments: ["@glome_api.user.repository"]
        arguments: ["%glome_api.users%"]

    glome_api.auth_code.manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManagerForClass
        arguments: ["%glome_api.auth_code.class%"]

    glome_api.user.manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManagerForClass
        arguments: ["%glome_api.user.class%"]

    glome_api.auth_code_manager:
        class: "%glome_api.auth_code_manager.class%"
        arguments: ["@glome_api.auth_code.manager", "%glome_api.auth_code.class%"]

    glome_api.token.controller:
        class: "%glome_api.token.controller.class%"
        arguments: ["@glome_api.oauth.server"]

    glome_api.oauth.storage:
        class: "%glome_api.oauth.storage.class%"
        public: false
        arguments:
            - "@fos_oauth_server.client_manager"
            - "@fos_oauth_server.access_token_manager"
            - "@fos_oauth_server.refresh_token_manager"
            - "@fos_oauth_server.auth_code_manager"
            - "@?fos_oauth_server.user_provider"
            - "@security.encoder_factory"
            - "@glome_api.user.manager"

    glome_api.oauth.server:
        class: "%glome_api.oauth.server.class%"
        arguments: ["@glome_api.oauth.storage", "%fos_oauth_server.server.options%"]
